/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  CipherScore,
  CipherScoreInterface,
} from "../../contracts/CipherScore";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint32[]",
        name: "inputs",
        type: "uint32[]",
      },
    ],
    name: "calculateEncryptedScore",
    outputs: [
      {
        internalType: "uint32",
        name: "score",
        type: "uint32",
      },
      {
        internalType: "bool",
        name: "approved",
        type: "bool",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610277806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c8063dc19c98e14610030575b600080fd5b61004361003e366004610134565b610063565b6040805163ffffffff909316835290151560208301520160405180910390f35b60008060008360038151811061007b5761007b6101f9565b602002602001015184600281518110610096576100966101f9565b6020026020010151856001815181106100b1576100b16101f9565b6020026020010151866000815181106100cc576100cc6101f9565b60200260200101516100de919061020f565b6100e8919061020f565b6100f2919061020f565b94600a63ffffffff871611945092505050565b634e487b7160e01b600052604160045260246000fd5b803563ffffffff8116811461012f57600080fd5b919050565b6000602080838503121561014757600080fd5b823567ffffffffffffffff8082111561015f57600080fd5b818501915085601f83011261017357600080fd5b81358181111561018557610185610105565b8060051b604051601f19603f830116810181811085821117156101aa576101aa610105565b6040529182528482019250838101850191888311156101c857600080fd5b938501935b828510156101ed576101de8561011b565b845293850193928501926101cd565b98975050505050505050565b634e487b7160e01b600052603260045260246000fd5b63ffffffff81811683821601908082111561023a57634e487b7160e01b600052601160045260246000fd5b509291505056fea2646970667358221220685cef00ea7398059a6b19de4da2ab0a262052730872fa59a8aa186bb6e0d51f64736f6c63430008180033";

type CipherScoreConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: CipherScoreConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class CipherScore__factory extends ContractFactory {
  constructor(...args: CipherScoreConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      CipherScore & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): CipherScore__factory {
    return super.connect(runner) as CipherScore__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): CipherScoreInterface {
    return new Interface(_abi) as CipherScoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): CipherScore {
    return new Contract(address, _abi, runner) as unknown as CipherScore;
  }
}
